CREATE TABLE IF NOT EXISTS Images
(
    ImageID INTEGER PRIMARY KEY AUTOINCREMENT,
    Filename TEXT NOT NULL,
    Prompt TEXT NOT NULL,
    EnhancedPrompt TEXT,
    Width INTEGER NOT NULL,
    Height INTEGER NOT NULL,
    Steps INTEGER NOT NULL,
    Seed INTEGER,
    Model TEXT,
    CreatedDate TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Users (
    UserID INTEGER PRIMARY KEY AUTOINCREMENT,
    Username TEXT NOT NULL UNIQUE,
    PasswordHash TEXT NOT NULL,
    PasswordSalt TEXT NOT NULL,
    CreatedDate TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Sessions (
    SessionID TEXT PRIMARY KEY,
    UserID INTEGER NOT NULL,
    CreatedDate TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ExpiresDate TEXT NOT NULL,
    FOREIGN KEY(UserID)
        REFERENCES Users(UserID)
        ON DELETE CASCADE
);
